let excuses = ["I was testing a new mouse sensitivity setting, things got chaotic.",
"My cat decided my keyboard was a better play area.",
"Power outage struck right in the middle of the match.",
"Sudden pizza delivery, priorities, you know?",
"Neighbor's WiFi suddenly went wonky.",
"Accidentally minimized the game while clutching.",
"Just got a call from the boss  emergency work task!",
"Wanted to give opponents a fighting chance, went easy.",
"In the midst of a heated match, my coffee spilled catastrophe.",
"Little sibling tripped over the power cord, game over.",
"Had to answer the door for unexpected package delivery.",
"Critical Windows update happened without any warning.",
"New game update, had to restart in the middle of a round.",
"Had to deal with an IRL 'defusing' situation  plumbing issues!",
"Smoke alarm went off; burnt toast crisis in the kitchen.",
"Emergency remote work meeting  had to Alt+F4 my way out.",
"Neighbor's cat walked on my keyboard, chaos ensued.",
"Fell victim to the classic 'cat on lap' distraction.",
"Suddenly became the designated tech support for grandma.",
"Crazy thunderstorm  lost power for a moment.",
"Realized I left the stove on, had to save dinner!",
"Had to break up a sibling fight; family first, right?",
"Unexpected fire drill  had to evacuate mid-game.",
"Internet provider decided it was maintenance time.",
"Lost track of time, had to attend an urgent appointment.",
"Neighbor's loud party forced me to mute the game audio.",
"Puppy mistook my controller for a chew toy.",
"Neighbor needed urgent tech help  played IT support.",
"Sudden nosebleed; had to pause for cleanup.",
"Locked myself out; had to deal with locksmith chaos.",
"Dropped my headset  spent crucial seconds untangling.",
"Wanted to give the opponents a sporting chance; went AFK.",
"Got too engrossed in watching cat videos during respawn.",
"Family movie night started earlier than expected.",
"Sunset was too beautiful  got distracted gazing out the window.",
"Dust storm hit; had to secure the windows and close the blinds.",
"Unexpected visit from a long-lost friend; priorities, right?",
"Suddenly remembered a forgotten appointment; abrupt exit.",
"Power nap turned into an unintended full-blown nap.",
"Neighbor's kid needed help with homework  real-life MVP.",
"Neighbor's WiFi password changed; had to reconnect.",
"Babysitting duty called; kids are demanding taskmasters.",
"Had a spider situation  arachnophobia kicked in.",
"Phone call from the future self  time travel complications.",
"Pet turtle made a daring escape; had to conduct a rescue mission.",
"Unexpected wardrobe malfunction  needed a quick fix.",
"Late-night snack attack; had to rustle up something to eat.",
"Neighbor's kid challenged me to a game of 'Who Can Scream Louder.'",
"Suddenly remembered I left the laundry running; clothes crisis!",
"Received a surprise parcel; had to unwrap it immediately.",
"Neighbor's lawnmower decided it was prime gaming time.",
"Pulled an all-nighter, nodding off mid-match  sleep claimed me.",
"Sudden onset of hiccups; had to deal with the annoyance.",
"Bumped my desk; monitor went into a psychedelic frenzy.",
"Neighbor's drone got stuck in my window; rescue mission required.",
"Wanted to test the theory of 'can you really fry an egg on a PC?'",
"Sudden craving for cookies; had to bake a batch mid-game.",
"Neighbor's cat stole my gaming chair; negotiation was futile.",
"Decided to multitask  playing and solving a Rubik's Cube.",
"Postman knocked loudly; had to sign for an unexpected package.",
"Sudden dance-off invitation from a sibling; how could I refuse?",
"Thought I heard a ghost; had to investigate the spooky noise.",
"Family-wide rock-paper-scissors tournament called for immediate participation.",
"Attempting to set a world record for the longest yodel.",
"Wanted to see if I could break the land speed record for room-to-fridge dash.",
"Inspiration struck; needed to compose a haiku for the in-game chat.",
"Received a sudden telepathic distress call from a fellow gamer; had to assist.",
"Attempting to find the meaning of life in the bottom of a bag of chips.",
"Had to referee a heated debate on the best flavor of ice cream in the family.",
"Decided to see if I could break the world record for most consecutive high-fives.",
"Sudden urge to practice interpretive dance; Valorant can wait.",
"Embarked on a quest to find the perfect meme to share in the in-game chat.",
"Neighbor needed someone to hold their ladder for an impromptu rooftop repair.",
"Attempted to break the world record for the longest time spent balancing a book on my head.",
"Engaged in an intense thumb-wrestling match with an imaginary opponent.",
"Emergency sock puppet show for a captive audience (myself).",
"Suddenly became the protagonist in my own impromptu interpretative dance musical.",
"Participating in an impromptu staring contest with the mirror  a battle of wills.",
"Embarked on a mission to find the missing sock that eluded me for days.",
"Attempting to break the record for the most consecutive successful attempts at catching grapes in my mouth.",
"Testing the theory that playing Valorant blindfolded enhances my other senses.",
"Engaged in a heated debate with my reflection over who gets to control the mouse.",
"Attempting to set a new world record for the fastest time spent untangling headphone wires.",
"Emergency snack creation time  the world needed to witness my instant ramen masterpiece.",
"Spontaneous interpretive dance session to the rhythm of the in-game gunfire.",
"Went on an expedition to explore the mystical land behind my gaming desk.",
"Attempting to break the world record for the longest time spent naming every color I could think of.",
"Urgent mission to discover the source of a mysterious smell in my room.",
"Embarked on a quest to find the perfect playlist for optimal gaming performance.",
"Attempting to communicate with extraterrestrial beings using Morse code on the keyboard.",
"Engaged in a heated debate with my conscience over the moral implications of virtual combat.",
"Decided to test the theory that playing with oven mitts improves gaming dexterity.",
"Emergency doodle session  the world needed to see my masterpiece on the back of an old receipt.",
"Trying out a new chair spin technique; got dizzy mid-game.",
"Unexpected spider sighting; arachnophobia kicked in.",
"Sudden urge to rearrange my desk for better feng shui.",
"Neighbor's dog challenged me to a staring contest; couldn't resist.",
"Fell into the rabbit hole of watching baby animal videos mid-round.",
"Decided to test if playing upside down improves reaction time.",
"Kitchen dance party broke out; had to join in.",
"Neighbor needed help finding their missing remote; became the hero.",
"Attempting to break the record for most creative snack assembly.",
"Lost track of time admiring the beauty of my own hand movements.",
"Trying to set a record for the longest time spent counting ceiling tiles.",
"Embarked on a quest to find the perfect gaming playlist.",
"Unexpected mirror pep talk session to boost in-game confidence.",
"Attempting to break the world record for the loudest potato chip crunch.",
"Received a mysterious package; had to investigate its contents.",
"Sudden fascination with the concept of playing with chopsticks as controllers.",
"Lost a bet and had to attempt playing with mittens for a round.",
"Accidentally activated voice command mode; chaos ensued.",
"Urgent mission to find the source of an elusive background noise.",
"Attempting to break the record for the most creative keyboard drumming.",
"Kitchen experiment time  was trying to create a new snack sensation.",
"Decided to play blindfolded to enhance my 'gaming senses.'",
"Neighbor needed help untangling Christmas lights; gaming break ensued.",
"Attempting to break the record for the longest time spent juggling.",
"Engaged in a heated debate with a houseplant over gaming strategies.",
"Family sing-along started; couldn't resist joining the chorus.",
"In the middle of testing out a theory  can you play with oven mitts?",
"Trying out the 'random key pressing' technique for optimal gaming success.",
"Fell into the black hole of watching 'how it's made' videos during respawn.",
"Embarked on a quest to find the lost TV remote for the entire household.",
"Unexpected sock puppet theater session; my hand stole the show.",
"Attempting to break the world record for the fastest in-game snack consumption.",
"Lost in a daydream about the perfect in-game victory dance.",
"Attempting to set a record for the most consecutive successful chair spins.",
"Sudden craving for a sandwich; had to create the ultimate mid-game snack.",
"Received an unexpected video call; had to multitask gaming and conversation.",
"Trying to break the record for the most creative use of office supplies during gaming.",
"Neighbor needed a dance partner for an impromptu virtual dance-off.",
"Embarked on a quest to find the perfect gaming snack combination.",
"Trying out the 'random mouse clicking' strategy; results were questionable.",
"Attempting to break the world record for the fastest mouse-clicking speed.",
"Sudden urge to test if playing with sunglasses on enhances my focus.",
"Family-wide debate over the best pizza toppings required my attention.",
"Neighbor challenged me to a simultaneous game of virtual charades.",
"Attempting to break the record for the longest time spent air drumming to the game soundtrack.",
"Lost in thought pondering the meaning of life; respawn took longer than expected.",
"Received a surprise package; had to open it immediately for in-game luck.",
"Engaged in a heated debate with a household pet over the best gaming strategy.",
"Trying out the 'keyboard as a drum set' technique; rhythm was questionable.",
"Embarked on a quest to find the perfect gaming chair adjustment.",
"Lost track of time staring at my own reflection in the monitor.",
"Attempting to break the world record for the fastest snack retrieval from the kitchen.",
"Sudden fascination with the concept of playing with a TV remote as a controller.",
"Kitchen dance party broke out; had to showcase my moves mid-round.",
"Trying out the 'play with your feet' challenge; results were less than stellar.",
"Attempting to break the record for the longest time spent naming household items.",
"Sudden desire to test if playing with a blindfold enhances my gaming instincts.",
"Embarked on a quest to find the perfect gaming chair spin technique.",
"Neighbor's cat challenged me to a staring contest; couldn't resist.",
"Lost in thought contemplating the mysteries of the universe; respawn took a backseat.",
"Received a mysterious phone call; had to take a break to investigate.",
"Attempting to break the world record for the fastest snack consumption during a respawn.",
"Engaged in a heated debate with a houseplant over the best gaming snack.",
"Trying out the 'play with your elbows' challenge; results were comical.",
"Attempting to set a record for the most creative use of household items during gaming.",
"Embarked on a quest to find the perfect gaming chair adjustment.",
"Lost track of time admiring the beauty of my own hand movements.",
"Trying to break the record for the longest time spent naming ceiling tiles.",
"Attempting to set a record for the loudest potato chip crunch.",
"Engaged in a heated debate with a houseplant over gaming strategies.",
"Family sing-along started; couldn't resist joining the chorus.",
"In the middle of testing out a theory  can you play with oven mitts?",
"Trying out the 'random key pressing' technique for optimal gaming success.",
"Fell into the black hole of watching 'how it's made' videos during respawn.",
"Embarked on a quest to find the lost TV remote for the entire household.",
"Attempting to break the world record for the fastest in-game snack consumption.",
"Lost in a daydream about the perfect in-game victory dance.",
"Attempting to break the record for the most consecutive successful chair spins.",
"Sudden craving for a sandwich; had to create the ultimate mid-game snack.",
"Received an unexpected video call; had to multitask gaming and conversation.",
"Trying to break the record for the most creative use of office supplies during gaming.",
"Attempting to break the world record for the fastest mouse-clicking speed.",
"Sudden urge to test if playing with sunglasses on enhances my focus.",
"Family-wide debate over the best pizza toppings required my attention.",
"Neighbor challenged me to a simultaneous game of virtual charades.",
"Attempting to break the record for the longest time spent air drumming to the game soundtrack.",
"Lost in thought pondering the meaning of life; respawn took longer than expected.",
"Received a surprise package; had to open it immediately for in-game luck.",
"Engaged in a heated debate with a household pet over the best gaming strategy.",
"Trying out the 'keyboard as a drum set' technique; rhythm was questionable.",
"Attempting to break the record for the fastest snack retrieval from the kitchen.",
"Sudden fascination with the concept of playing with a TV remote as a controller.",
"Kitchen dance party broke out; had to showcase my moves mid-round.",
"Attempting to break the world record for the longest time spent naming household items.",
"Sudden desire to test if playing with a blindfold enhances my gaming instincts.",
"Embarked on a quest to find the perfect gaming chair spin technique.",
"Neighbor's cat challenged me to a staring contest; couldn't resist.",
"Lost in thought contemplating the mysteries of the universe; respawn took a backseat.",
"Received a mysterious phone call; had to take a break to investigate.",
"Attempting to break the world record for the fastest snack consumption during a respawn."];




let button = document.querySelector("#generate");
let text = document.querySelector("p");
let dark = document.querySelector("#dark-mode");
let hero = document.querySelector(".hero");
let mode = document.querySelector("span");

button.onclick = () => {
    const randomElement = excuses[Math.floor(Math.random() * excuses.length)];
    text.innerText = randomElement;
}

// dark.onclick = () => {
//     hero.style.backgroundColor = 'black';
//     text.style.color = 'White';
//     mode.innerText = "Light Mode";

//     dark.onclick = () => {
//         hero.style.backgroundColor = '#C1CEFE';
//         text.style.color = '#023e8a';
//         mode.innerText = "Dark Mode";
//     }
// }

let currentMode = "Dark Mode";
dark.addEventListener("click", changemode = () => {
    if(currentMode === "Dark Mode")
    {
        currentMode = "Light Mode";
        hero.style.backgroundColor = 'black';
        text.style.color = 'White';
        mode.innerText = currentMode;
    }
    else 
    {
        currentMode = "Dark Mode";
        hero.style.backgroundColor = '#C1CEFE';
        text.style.color = '#023e8a';
        mode.innerText = currentMode;
    }
})
